### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by Ravenstine** [Ravenstine/skills-in-pills#6]
Data persistence is kinda sorta implemented... I just haven't had a whole lot of time to thoroughly develop and test them out.

This is how it currently works:

`lib/persist.js` is called at the end of each session.  If `process.env.DYNAMODB_TABLE_NAME` is defined, `lib/adapters/dynamodb.js` will be used to PUT the data for the current user from the DynamoDB table.  Likewise, if `process.env.COUCHDB_DATABASE_NAME` is defined, user data is sent to the CouchDB instance specified with `process.env.COUCHDB_HOST`.  Otherwise, a null adapter is used and no data is saved and no requests are made.

Likewise, the data gets retrieved at the beginning of each session with `lib/remember.js`.  However, the data does not get loaded into the session unless a label that gets evaluated has the key `restore: session` or `restore: attributes`.  `restore: session` restores everything including the current navigation whereas `restore: attributes` only restores set attributes.

The way you can know when you might want to restore user data is if the `SavedSessionAvailable` event is used.  So in a label you would do something like:

```yaml
Some Label:
  events:
    SavedSessionAvailable:
      go to: Ask To Restore
  go to: I Don't Know You

Ask To Restore:
  ask: Have we met before?
  utterances:
    yes:
      go to: I Know You
    no:
      go to: I Don't Know You

I Know You:
  restore: attributes
  speak: Good to see you again, ${firstName}!

I Don't Know You:
  speak: I don't know you.
  ask: What's your name?
  utterances:
    ( |i'm|my name is) ${firstName}:
      set:
        slot: firstName
      go to: Now I Know You

Now I Know You:
  speak: Nice to meet you, ${firstName}!
```

Thing is, I'm not sure I really like this.  Will write more about it later.
